services:
  backend1:
    image: ronssm/copirinhago:latest
    environment:
      - REDIS_CONN=redis:6379
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
  backend2:
    image: ronssm/copirinhago:latest
    environment:
      - REDIS_CONN=redis:6379
      - LOG_LEVEL=ERROR
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "120MB"
  haproxy:
    image: haproxy:2.8-alpine
    depends_on:
      - backend1
      - backend2
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --tcp-keepalive 60 --timeout 0
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 175M
          cpus: '0.6'
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
